#!/usr/bin/env python3
"""Plot route-node CSV output from routing-alt-benchmark on a processed GraphML map."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import osmnx as ox


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--graphml", required=True, type=Path)
    parser.add_argument(
        "--routes", required=True, type=Path, help="route-nodes CSV from routing-alt-benchmark"
    )
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    graph = ox.load_graphml(args.graphml)
    routes: dict[tuple[str, str, str, str], list[tuple[int, int]]] = {}
    with args.routes.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        required = {"profile", "pair_id", "repetition", "route_index", "node_index", "osm_node_id"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"route CSV is missing columns: {', '.join(sorted(missing))}")
        for row in reader:
            if not row["osm_node_id"]:
                raise ValueError("route CSV has no OSM IDs; use a map generated by scripts/build_map.py")
            key = (row["profile"], row["pair_id"], row["repetition"], row["route_index"])
            routes.setdefault(key, []).append((int(row["node_index"]), int(row["osm_node_id"])))
    if not routes:
        raise ValueError("route CSV contains no routes")

    ordered_routes = [
        [osm_id for _, osm_id in sorted(nodes)] for _, nodes in sorted(routes.items())
    ]
    missing_nodes = sorted({node for route in ordered_routes for node in route if node not in graph})
    if missing_nodes:
        raise ValueError(f"{len(missing_nodes)} route OSM IDs are absent from GraphML")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    colors = plt.cm.tab10.colors
    route_colors = [colors[index % len(colors)] for index in range(len(ordered_routes))]
    fig, _ = ox.plot_graph_routes(
        graph,
        ordered_routes,
        route_colors=route_colors,
        route_linewidth=3,
        node_size=0,
        show=False,
        close=False,
    )
    fig.savefig(args.output, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved {len(ordered_routes)} plotted routes to {args.output}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
